[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions/"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.0.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  target = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]
